name: CI Validation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  validate:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Validate HTML
        run: |
          if [ ! -f index.html ]; then
            echo "ERROR: index.html not found!"
            exit 1
          fi
          echo "✓ index.html exists"
      
      - name: Validate README
        run: |
          if [ ! -f README.md ]; then
            echo "ERROR: README.md not found!"
            exit 1
          fi
          echo "✓ README.md exists"
      
      - name: Validate LICENSE
        run: |
          if [ ! -f LICENSE ]; then
            echo "ERROR: LICENSE not found!"
            exit 1
          fi
          if ! grep -q "MIT License" LICENSE; then
            echo "ERROR: LICENSE is not MIT!"
            exit 1
          fi
          echo "✓ LICENSE is MIT"
      
      - name: Check HTML structure
        run: |
          if ! grep -q "<!DOCTYPE html>" index.html; then
            echo "WARNING: Missing DOCTYPE declaration"
          fi
          if ! grep -q "<html" index.html; then
            echo "ERROR: Invalid HTML structure"
            exit 1
          fi
          echo "✓ HTML structure valid"
      
      - name: Check Bootstrap CDN
        run: |
          if grep -q "bootstrap" index.html; then
            echo "✓ Bootstrap detected"
          else
            echo "WARNING: Bootstrap not found (may not be required)"
          fi
      
      - name: Summary
        run: |
          echo "========================================"
          echo "Repository validation completed"
          echo "========================================"
          echo "Files checked:"
          ls -lh index.html README.md LICENSE
          echo ""
          echo "HTML file size:"
          wc -c index.html | awk '{print $1 " bytes"}'
